### ISSUE TITLE
Missing file dependency?

### ISSUE THREAD

**Issue by Hillb** [omniupdate/example-code-blogs#1]
When deployed, the XSL references a dependency at /_resources/xsl/_shared/functions.xsl. While other XSL dependencies were found in a subfolder, this file appears to not exist. A similarly named file was found at /_resources/xsl/blog/blog-functions.xsl, but this does not appear to be the same file as is being requested (duplicating and renaming this file simply causes a large number of errors to be generated).

**Comment by blaird83** [comment]
Updates have been applied to cleanup files and add referenced resources to provide a more comprehensive starting point, which should resolve this issue.

**Comment by uimatters** [comment]
Hi Brian, I found another one:

If you work out of the /php/ subfolder, there is a missing XSL file (but it IS in the c++ subfolder):
/_resources/xsl/blog/listing-preview.xsl
